---
- name: Update apt packages
  become: yes
  apt:
    update_cache: yes

- name: Upgrade packages
  become: true
  apt:
    upgrade: "yes"

- name: Remove redundant dependencies
  become: yes
  apt:
    autoremove: yes

- name: Install dependencies [NodeJS, npm]
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: Install pm2
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: List workspace
  become: yes
  shell: |
    ls -R
    pm2 start npm --name backend

- name: Unarchive backend js files
  become: yes
  unarchive:
    src: /root/project/backend.tar.gz
    dest: .

- name: Initiate server
  become: yes
  shell: |
    ll
    pm2 start npm --name backend